# Site settings
title: Dev Frame
email: a.karimi.k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Geeky experiences of a software developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 4m1rk
github_username: amirkarimi

excerpt_separator: <!--more-->

comments :
  provider : disqus
  disqus :
    short_name : amirkarimigithub

analytics :
  provider : google
  google : 
      tracking_id : 'UA-49671611-5'

# Build settings
markdown: kramdown

